directories:
  vector_database_directory: data/vector_db
  csv_all_product_directory: data/product_final_300_extract.xlsx
  csv_dieu_hoa_directory: data/dieu_hoa.csv
  csv_question_user: data/Cau_hoi_thuong_gap.csv
  
llm_config:
  rag_model: gpt-4o-mini-2024-07-18
  chatchit_model: gpt-4o-mini-2024-07-18
  temperature_rag: 0.0
  temperature_chat: 1.0
  max_token: 1024
  
retriever_config:
  embedding_baai: BAAI/bge-base-en-v1.5
  vector_embed_baai: 768
  embedding_openai: text-embedding-ada-002
  vector_embed_openai: 1536
  top_k_product: 4
  top_k_question: 1
  top_p: 0.9

chunk_config:
  chunk_size: 1248
  chunk_overlap: 200

# 82 -> 95: LSD